Resources:
    CloudwatchInvokePermission:
        DependsOn: FetchDashliveDashscoreLambdaFunction
        Type: AWS::Lambda::Permission
        Properties:
            FunctionName:
                'Fn::GetAtt': [FetchDashliveDashscoreLambdaFunction, Arn]
            Action: 'lambda:InvokeFunction'
            SourceArn: arn:aws:events:${self:provider.region}:${self:custom.aws.accountId}:*/*
            Principal: 'events.amazonaws.com'
