Conditions:
    isLocal:
        Fn::Equals:
            - ${self:provider.stage}
            - development
Resources:
    AssetBucket:
        Type: AWS::S3::Bucket
        Condition: isLocal
        Properties:
            BucketName: sw-asset-bucket
    DataBucket:
        Type: AWS::S3::Bucket
        Condition: isLocal
        Properties:
            BucketName: sw-data-bucket
