Resources:
    FifaTeamTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: fifa-team-topic
    FifaTeamQueueSubscription:
        DependsOn: EspnTeamQueue
        Type: 'AWS::SNS::Subscription'
        Properties:
            TopicArn: !Ref FifaTeamTopic
            Region: ${self:provider.region}
            Endpoint: !GetAtt
                - EspnTeamQueue
                - Arn
            Protocol: sqs
            RawMessageDelivery: 'true'
