Resources:
    FifaTeamTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: fifa-team-topic
    FifaTeamQueueSubscription:
        DependsOn: ScoreboardTeamQueue
        Type: 'AWS::SNS::Subscription'
        Properties:
            TopicArn: !Ref FifaTeamSns
            Endpoint: !GetAtt
                - ScoreboardTeamQueue
                - Arn
            Protocol: sqs
            RawMessageDelivery: 'true'
