Resources:
    FifaTeamQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: FifaTeamQueue
    FifaPlayerQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: FifaPlayerQueue
