Resources:
    EspnTeamQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: espn-team-queue
            VisibilityTimeout: '600'
    EspnPlayerQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: espn-player-queue
            VisibilityTimeout: '600'
    WhoscoreLeagueQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: whoscore-league-link
            VisibilityTimeout: '600'
    RatingQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: rating-queue
            VisibilityTimeout: '600'
    EspnTeamQueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            PolicyDocument:
                Version: '2012-10-17'
                Id: sns-queue-subscription
                Statement:
                    - Sid: Allow-SNS-SendMessage
                      Effect: Allow
                      Principal: '*'
                      Action:
                          - sqs:SendMessage
                      Resource:
                          Fn::GetAtt:
                              - EspnTeamQueue
                              - Arn
                      Condition:
                          ArnEquals:
                              aws:SourceArn:
                                  Ref: FifaTeamTopic
            Queues:
                - Ref: EspnTeamQueue
