export const COOKIE_JWT_PAYLOAD = 'X-AUTH-JWT-PAYLOAD';
export const COOKIE_JWT_SIGNATURE = 'X-AUTH-JWT-SIGNATURE';
export const COOKIE_REFRESH_TOKEN = 'X-AUTH-REFRESH-TOKEN';
export const COOKIE_CSRF = 'XSRF-TOKEN';
export const COOKIE_REFERRER = 'Referrer';
export const HEADER_SERVER_SIDE = 'X-SERVER-SIDE';
