export const ADD_PLAYER_TO_LINEUP = Symbol('ADD_PLAYER_TO_LINEUP');
export const CLEAR_LINEUP_POSITION = Symbol('CLEAR_LINEUP_POSITION');
export const FILL_POSITIONS = Symbol('FILL_POSITIONS');
export const REMOVE_PLAYER_FROM_LINEUP = Symbol('REMOVE_PLAYER_FROM_LINEUP');
export const SWAP_PLAYERS = Symbol('SWAP_PLAYERS');
export const CHANGE_STRATEGY = Symbol('CHANGE_STRATEGY');
export const FILL_POSITION_SUCCESS = Symbol('FILL_POSITION_SUCCESS');
