export const FETCH_LEAGUES = Symbol('FETCH_LEAGUES');
export const FETCH_LEAGUES_SUCCESS = Symbol('FETCH_LEAGUES_SUCCESS');

export const FETCH_LEAGUE_STANDING = Symbol('FETCH_LEAGUE_STANDING');
export const FETCH_LEAGUE_STANDING_SUCCESS = Symbol('FETCH_LEAGUE_STANDING_SUCCESS');
export const FETCH_LEAGUE_STANDING_ERROR = Symbol('FETCH_LEAGUE_STANDING_ERROR');
