export const FETCH_MY_PLAYERS_SUCCESS = Symbol('FETCH_MY_PLAYERS_SUCCESS');
export const FETCH_MY_PLAYERS_ERROR = Symbol('FETCH_MY_PLAYERS_ERROR');
export const FETCH_MY_PLAYERS = Symbol('FETCH_MY_PLAYERS');

export const FETCH_MY_BETTING_SUCCESS = Symbol('FETCH_MY_BETTING_SUCCESS');
export const FETCH_MY_BETTING = Symbol('FETCH_MY_BETTING');

export const UPDATE_RATING = Symbol('UPDATE_RATING');
export const UPDATE_TOKEN = Symbol('UPDATE_TOKEN');
