export const FETCH_MY_PLAYERS_SUCCESS = Symbol('FETCH_MY_PLAYERS_SUCCESS');
export const FETCH_MY_PLAYERS_ERROR = Symbol('FETCH_MY_PLAYERS_ERROR');
export const FETCH_MY_PLAYERS = Symbol('FETCH_MY_PLAYERS');
