.only-default: &only-default
    refs:
        - master
        - testing
        - release
        - merge_requests
        - tags

image: sportywide/sportywide-node-alpine

stages:
    - install_dependencies
    - build
    - test

install_dependencies:
    stage: install_dependencies
    script:
        - lerna bootstrap -- --ci --no-optional && npx link-parent-bin
    cache:
        paths:
            - node_modules/
            - packages/*/node_modules
    only:
        <<: *only-default

build:
    stage: build
    only:
        <<: *only-default
    cache:
        paths:
            - node_modules/
            - packages/*/node_modules
        policy: pull
    script:
        - lerna run build --stream
test:
    stage: test
    only:
        <<: *only-default
    cache:
        paths:
            - node_modules/
            - packages/*/node_modules
        policy: pull
    script:
        - npx gulp test --coverage
        - bash <(curl -s https://codecov.io/bash)
