.only-default: &only-default
    refs:
        - master
        - testing
        - release
        - merge_requests
        - tags

image: sportywide/sportywide-node-alpine

stages:
    - install_dependencies
    - build
    - test

install_dependencies:
    stage: install_dependencies
    script:
        - npm cache clear --force
        - npm run bootstrap:ci
    cache:
        key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
        paths:
            - node_modules/
            - packages/*/node_modules
    only:
        <<: *only-default
        changes:
            - package-lock.json

build:
    stage: build
    only:
        <<: *only-default
    cache:
        key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
        paths:
            - node_modules/
            - packages/*/node_modules
        policy: pull
    script:
        - npx lerna run build --stream
test:
    stage: test
    only:
        <<: *only-default
    cache:
        key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
        paths:
            - node_modules/
            - packages/*/node_modules
        policy: pull
    script:
        - npm run test:coverage
        - bash <(curl -s https://codecov.io/bash)
