image: sportywide/sportywide-node-alpine

stages:
    - install_dependencies
    - build
    - test
install_dependencies:
    stage: install_dependencies
    script:
        - npm cache clear --force
        - npm run bootstrap:ci
    cache:
        key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
        paths:
            - node_modules/
            - packages/*/node_modules
    only:
        changes:
            - package-lock.json

build:
    stage: build
    cache:
        key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
        paths:
            - node_modules/
            - packages/*/node_modules
        policy: pull
    script:
        - npx lerna run build --stream
test:
    stage: test
    cache:
        key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
        paths:
            - node_modules/
            - packages/*/node_modules
        policy: pull
    script:
        - npm run test:coverage
