version: '3.5'
services:
    base:
        image: sportywide-base
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        networks:
            - sportywide-backend
            - sportywide-frontend
        environment:
            NO_OPTIONAL: 1
            NODE_ENV: development
        command: npm run install:dependencies
        volumes:
            - .:/opt/app
            - node_modules:/opt/app/node_modules
    web:
        build:
            context: .
            dockerfile: ./packages/sw-web/Dockerfile
            target: base
        ports:
            - 3000:3000
        command: dev
        depends_on:
            - base
        labels:
            - 'traefik.frontend.rule=Host:www.sportywidedev.com,sportywidedev.com'
            - 'traefik.port=3000'
        volumes:
            - .:/opt/app
            - node_modules:/opt/app/node_modules
        networks:
            - sportywide-frontend
    api:
        build:
            context: .
            dockerfile: ./packages/sw-api/Dockerfile
            target: base
        ports:
            - 5000:5000
            - 9229:9229
        command: dev
        labels:
            - 'traefik.frontend.rule=Host:api.sportywidedev.com'
            - 'traefik.port=5000'
        environment:
            WAIT_HOSTS: postgres:5432,redis:6379
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DATABASE: ${POSTGRES_DB}
        depends_on:
            - base
        volumes:
            - .:/opt/app
            - node_modules:/opt/app/node_modules
        networks:
            - sportywide-backend
    email:
        build:
            context: .
            dockerfile: ./packages/sw-email/Dockerfile
            target: base
        command: dev
        environment:
            WAIT_HOSTS: redis:6379
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DATABASE: ${POSTGRES_DB}
        depends_on:
            - base
        ports:
            - 9230:9229
        volumes:
            - .:/opt/app
            - node_modules:/opt/app/node_modules
        networks:
            - sportywide-backend
networks:
    sportywide-frontend:
        external:
            name: sportywide-frontend
    sportywide-backend:
        external:
            name: sportywide-backend

volumes:
    node_modules:
