version: '3'
services:
    base:
        image: sportywide-base
        build:
            context: .
            dockerfile: Dockerfile
    web:
        build:
            context: .
            dockerfile: ./packages/sw-web/Dockerfile
        ports:
            - 3000:3000
        command: dev
        depends_on:
            - base
        volumes:
            - ./packages/sw-shared:/opt/app/packages/sw-shared
            - ./packages/sw-web:/opt/app/packages/sw-web
            - /opt/app/packages/sw-shared/node_modules
            - /opt/app/packages/sw-web/node_modules
    api:
        build:
            context: .
            dockerfile: ./packages/sw-api/Dockerfile
        ports:
            - 5000:5000
        command: dev
        environment:
            WAIT_HOSTS: mysql:3306
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        depends_on:
            - base
        volumes:
            - ./packages/sw-api:/opt/app/packages/sw-api
            - ./packages/sw-shared:/opt/app/packages/sw-shared
            - ./packages/sw-core:/opt/app/packages/sw-core
            - ./packages/sw-schema:/opt/app/packages/sw-schema
            - /opt/app/packages/sw-shared/node_modules
            - /opt/app/packages/sw-schema/node_modules
            - /opt/app/packages/sw-api/node_modules
            - /opt/app/packages/sw-core/node_modules
