version: '3'
services:
    postgres:
        image: sportywide/sportywide-postgres
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres:/var/lib/postgres/data
        ports:
            - '${POSTGRES_PORT}:5432'
    flyway:
        image: sportywide/sportywide-flyway
        command: -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate
        volumes:
            - './sql:/flyway/sql'
        environment:
            WAIT_HOSTS: postgres:5432
        depends_on:
            - postgres
    redis:
        image: sportywide/sportywide-redis
        volumes:
            - redis:/data
        ports:
            - '${REDIS_PORT}:6379'
    mailhog:
        image: sportywide/sportywide-mailhog
        ports:
            - '${MAILHOG_TRANSPORT_PORT}:1025'
            - '${MAILHOG_UI_PORT}:8025'
volumes:
    postgres:
    redis:
