version: '3'
services:
    mysql:
        image: sportywide/sportywide-mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - '${MYSQL_PORT}:3306'
    flyway:
        image: sportywide/sportywide-flyway
        command: -url=jdbc:mysql://mysql:3306/${MYSQL_DATABASE} -user=${MYSQL_USER} -password=${MYSQL_PASSWORD} migrate
        volumes:
            - './sql:/flyway/sql'
        environment:
            WAIT_HOSTS: mysql:3306
        depends_on:
            - mysql
    redis:
        image: sportywide/sportywide-redis
        volumes:
            - redis:/data
        ports:
            - '${REDIS_PORT}:6379'
    mailhog:
        image: sportywide/sportywide-mailhog
        ports:
            - '${MAILHOG_TRANSPORT_PORT}:1025'
            - '${MAILHOG_UI_PORT}:8025'
volumes:
    mysql:
    redis:
