version: '3.5'
services:
    api-test:
        image: sportywide/sportywide-base
        container_name: sw_api_test
        entrypoint: ['npx', 'gulp']
        command: api-test
        depends_on:
            - base
            - api
        volumes:
            - .:/opt/app
            - node_modules:/opt/app/node_modules
        environment:
            WAIT_HOSTS: api:5000
            WAIT_SLEEP_INTERVAL: 10
            WAIT_HOSTS_TIMEOUT: 120
        networks:
            - sw_net_backend
    test:
        image: sportywide/sportywide-base
        container_name: sw_test
        entrypoint: ['npx', 'gulp']
        command: ['test', '--full', '--colors']
        environment:
            POSTGRES__HOST: postgres
        depends_on:
            - base
            - api
        volumes:
            - .:/opt/app
            - node_modules:/opt/app/node_modules
        networks:
            - sw_net_backend
networks:
    sw_net_frontend:
        external:
            name: sw_net_frontend
    sw_net_backend:
        external:
            name: sw_net_backend
