version: '3.5'
services:
    node:
        container_name: sw_node
        image: sportywide/sportywide-node-alpine
        build:
            context: .
            dockerfile: Dockerfile
            target: node
    base:
        container_name: sw_base
        image: sportywide/sportywide-base
        depends_on:
            - node
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        networks:
            - sw_net_backend
            - sw_net_frontend
        environment:
            NO_OPTIONAL: 1
            NODE_ENV: development
        entrypoint: npm run install:dependencies -- -s
        volumes:
            - .:/opt/app
            - node_modules:/opt/app/node_modules
    web:
        container_name: sw_web
        image: sportywide/sportywide-web
        build:
            context: .
            dockerfile: ./packages/sw-web/Dockerfile
            target: base
        ports:
            - 3000:3000
        command: dev
        depends_on:
            - base
        labels:
            - 'traefik.frontend.rule=Host:www.sportywidedev.com,sportywidedev.com'
            - 'traefik.port=3000'
        volumes:
            - .:/opt/app
            - node_modules:/opt/app/node_modules
        networks:
            - sw_net_frontend
            - sw_net_backend
    api:
        container_name: sw_api
        image: sportywide/sportywide-api
        build:
            context: .
            dockerfile: ./packages/sw-api/Dockerfile
            target: base
        ports:
            - 5000:5000
            - 9229:9229
        command: dev
        labels:
            - 'traefik.frontend.rule=Host:api.sportywidedev.com'
            - 'traefik.port=5000'
        environment:
            WAIT_HOSTS: postgres:5432,redis:6379
            SW_POSTGRES_USER: ${SW_POSTGRES_USER}
            SW_POSTGRES_PASSWORD: ${SW_POSTGRES_PASSWORD}
            SW_POSTGRES_DB: ${SW_POSTGRES_DB}
            SW_FACEBOOK_CLIENT_SECRET: ${SW_FACEBOOK_CLIENT_SECRET}
            SW_GOOGLE_CLIENT_SECRET: ${SW_GOOGLE_CLIENT_SECRET}
            SW_MONGO_USER: ${SW_MONGO_USER}
            SW_MONGO_PASSWORD: ${SW_MONGO_PASSWORD}
            SW_MONGO_DB: ${SW_MONGO_DB}
        depends_on:
            - base
        volumes:
            - .:/opt/app
            - node_modules:/opt/app/node_modules
        networks:
            - sw_net_backend
    email:
        container_name: sw_email
        image: sportywide/sportywide-email
        build:
            context: .
            dockerfile: ./packages/sw-email/Dockerfile
            target: base
        command: dev
        environment:
            WAIT_HOSTS: redis:6379
            SW_POSTGRES_USER: ${SW_POSTGRES_USER}
            SW_POSTGRES_PASSWORD: ${SW_POSTGRES_PASSWORD}
            SW_POSTGRES_DB: ${SW_POSTGRES_DB}
        depends_on:
            - base
        ports:
            - 9230:9229
        volumes:
            - .:/opt/app
            - node_modules:/opt/app/node_modules
        networks:
            - sw_net_backend
networks:
    sw_net_frontend:
        external:
            name: sw_net_frontend
    sw_net_backend:
        external:
            name: sw_net_backend

volumes:
    node_modules:
        name: sw_volume_node_modules
