#! /usr/bin/env node
const { execSync } = require('child_process');

const packageName = process.argv[2];

let packageJson;
if (packageName) {
	packageJson = require(`${__dirname}/packages/${packageName}/package.json`);
} else {
	packageJson = require(`${__dirname}/package.json`);
}

console.info(
	execSync(`npx semver ${packageJson.version} -i minor`, {
		encoding: 'utf-8',
	}).trim()
);
