debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
	[entryPoints.http]
		address = ":80"
  	[entryPoints.http.redirect]
		entryPoint = "https"
  	[entryPoints.https]
		address = ":443"
		compress = true
	[entryPoints.https.redirect]
		regex = "^https://sportywidedev.com/(.*)"
		replacement = "https://www.sportywidedev.com/$1"
		permanent = true	
  	[entryPoints.https.tls]
		[[entryPoints.https.tls.certificates]]
			certFile = "/certs/sportywide-cert.pem"
			keyFile = "/certs/sportywide-key.pem"
  	[entryPoints.traefik]
  		address = ":8080"

[api]
entryPoint = "traefik"
dashboard = true

[retry]

[docker]
endpoint = "tcp:///var/run/docker.sock"
exposedByDefault = false

[file]
watch = true

[backends]
	[backends.swapi]
		[backends.swapi.servers.swapi]
				url = "http://192.168.50.1:5000"
	[backends.swweb]
        [backends.swweb.servers.swweb]
            url = "http://192.168.50.1:3000"

[frontends]
        [frontends.swapi]
                backend = "swapi"
        [frontends.swapi.routes.swapi]
                rule = "Host:api.sportywidedev.com"
        [frontends.swweb]
                backend = "swweb"
        [frontends.swweb.routes.swweb]
                rule = "Host:www.sportywidedev.com,sportywidedev.com"