export const FETCH_BASIC_USER_PROFILE_SUCCESS = Symbol('FETCH_BASIC_USER_PROFILE_SUCCESS');
export const FETCH_EXTRA_USER_PROFILE_SUCCESS = Symbol('FETCH_EXTRA_USER_PROFILE_SUCCESS');
export const FETCH_USER_PROFILE = Symbol('FETCH_USER_PROFILE');
export const FETCH_BASIC_USER_PROFILE = Symbol('FETCH_BASIC_USER_PROFILE');
export const FETCH_EXTRA_USER_PROFILE = Symbol('FETCH_EXTRA_USER_PROFILE');
