export const FETCH_CHARACTER_SUCCESS = Symbol('FETCH_CHARACTER_SUCCESS');
export const FETCH_CHARACTER_FAILURE = Symbol('FETCH_CHARACTER_FAILURE');
export const START_FETCHING_CHARACTERS = Symbol('START_FETCHING_CHARACTERS');
export const STOP_FETCHING_CHARACTERS = Symbol('STOP_FETCHING_CHARACTERS');
