export const LOAD_USER_LEAGUES = Symbol('LOAD_USER_LEAGUES');
export const LOAD_USER_LEAGUE_SUCCESS = Symbol('LOAD_USER_LEAGUES_SUCCESS');
export const LEAVE_USER_LEAGUE = Symbol('LEAVE_USER_LEAGUE');
export const JOIN_USER_LEAGUE = Symbol('JOIN_USER_LEAGUE');
