service: sw-scheduling

provider:
    name: aws
    region: ap-southeast-2
    runtime: nodejs10.x
    stage: ${opt:stage, 'production'}

plugins:
    - serverless-webpack
    - serverless-offline
    - serverless-s3-local
    - serverless-dynamodb-local
    - serverless-iam-roles-per-function

custom:
    serverless-offline:
        port: 4000
    webpack:
        includeModules:
            packagePath: '../../package.json'
            forceInclude:
                - source-map-support
    s3:
        port: 6000
        directory: .s3
    dynamodb:
        readCapacity: 5
        writeCapacity: 5
        start:
            port: 5500
            migrate: true
            inMemory: false
            dbPath: .dynamodb

functions: ${file(resources/functions.yml)}
resources:
    - ${file(resources/s3.yml)}
