service: sw-scheduling

provider:
    name: aws
    region: ap-southeast-2
    runtime: nodejs10.x
    stage: ${opt:stage, 'production'}

plugins:
    - serverless-webpack
    - serverless-offline

custom:
    serverless-offline:
        port: 4000
    webpack:
        includeModules:
            packagePath: '../../package.json'
            forceInclude:
                - source-map-support

functions: ${file(resources/functions.yml)}
