service: sw-scheduling

provider:
    name: aws
    region: ap-southeast-2
    runtime: nodejs10.x
    stage: ${opt:stage, 'production'}

plugins:
    - serverless-webpack
    - serverless-offline-sqs
    - serverless-offline-sns
    - serverless-offline
    - serverless-s3-local
    - serverless-dynamodb-local
    - serverless-iam-roles-per-function

custom:
    serverless-offline:
        port: 4000
        host: 0.0.0.0
    aws:
        accountId: 409050499179
    webpack:
        includeModules:
            packagePath: '../../package.json'
            forceInclude:
                - source-map-support
    serverless-offline-sqs:
        autoCreate: true
        apiVersion: '2012-11-05'
        endpoint: http://0.0.0.0:9324
        region: ${self:provider.region}
        accessKeyId: root
        secretAccessKey: root
        skipCacheInvalidation: false
    serverless-offline-sns:
        port: 4002
        debug: false
        host: 0.0.0.0
        accountId: ${self:custom.aws.accountId}
    s3:
        port: 6000
        directory: .s3
    dynamodb:
        readCapacity: 5
        writeCapacity: 5
        start:
            port: 5500
            migrate: true
            inMemory: false
            dbPath: .dynamodb

resources:
    - ${file(resources/s3.yml)}
    - ${file(resources/sqs.yml)}
    - ${file(resources/sns.yml)}
functions: ${file(resources/functions.yml)}
