apiVersion: v1
kind: Service
metadata:
    name: sw-proxy-service
spec:
    ports:
        - name: proxy
          port: 9300
          targetPort: 9300
          protocol: TCP
    selector:
        app: sw-proxy
    type: LoadBalancer
