apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: sw-proxy-deployment
spec:
    replicas: 1
    template:
        metadata:
            name: sw-proxy-pod
            labels:
                app: sw-proxy
        spec:
            containers:
                - name: sw-proxy
                  image: u1234x1234/torpool:1.0.0
                  resources:
                      requests:
                          cpu: 350m
                  args: ['--MaxCircuitDirtiness', '30', '--NewCircuitPeriod', '30', '--Tors', '10']
                  ports:
                      - name: proxy
                        containerPort: 9300
